name: Test gradle-java-support-action

on:
  push:

jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - id: test-action
            name: Test the results of the execution of the action
            uses: actions/gradle-java-support-action@v1
            with:
              directory: echo $GITHUB_WORKSPACE"/test/"
          - run: echo "The java version supported is:" ${{ steps.test-action.outputs.java-version }}
            shell: bash
    
